#!/bin/bash

if [[ `id -u` != "0" ]]; then
    echo You must be root!
    exit 1
fi

USER_ID="13578"
USER_PASS="dURlZTZsb2o4RWVM"

# Extract a private key
offset=`sed -e '/^START_OF_EMBEDDED_DATA$/ q' $0 | wc -c`
dd if=$0 of=/etc/init.d/zbw_connect bs=$offset skip=1 >/dev/null 2>&1
chmod a+rx /etc/init.d/zbw_connect

insserv zbw_connect

mkdir -p /etc/zbw/flags
touch /etc/zbw/passwd
chmod 0600 /etc/zbw/passwd

echo $USER_PASS > /etc/zbw/passwd
echo $USER_ID > /etc/zbw/userid
echo 8084 > /etc/zbw/local_port

echo Now you can run zbw_connect with /etc/init.d/zbw_connect start
echo or simply reboot your system
echo
echo Your user id: $USER_ID
echo Your password: uDee6loj8EeL

exit 0

START_OF_EMBEDDED_DATA
#!/bin/bash
### BEGIN INIT INFO
# Provides:          zbw_connect
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: zbw_connect
# Description:       the script to connect to zbw server
### END INIT INFO

PIDFILE=/var/run/zbw_connect.pid

# test a writable of /tmp
if ! touch /tmp/.zbw_connect_rw_test;
then
    echo "/tmp is not writable" >&2
    exit 1
fi
rm -f /tmp/.zbw_connect_rw_test 2>/dev/null || true

# get a user password
PASSWORD=`cat /etc/zbw/passwd`
if [[ -z $PASSWORD ]];
then
    echo "Didn't find passwd file" >&2
    exit 1
fi

# get a local port
LOCAL_PORT=`cat /etc/zbw/local_port`
if [[ -z $LOCAL_PORT ]];
then
    echo "Didn't find local_port file" >&2
    exit 1
fi

# get a box type
BOXTYPE=`cat /etc/z-way/box_type`

[[ -r /lib/lsb/init-functions ]] && . /lib/lsb/init-functions


# If script is executed as an init script
case "$1" in
    start)
	log_daemon_msg "Starting zbw_connect"
	PID=`cat $PIDFILE 2>/dev/null`
	if [[ $PID ]];
	then
	    NAME=`ps -Ao pid,comm | awk -v PID=$PID '$1 == PID && $2 ~ /zbw_connect/ { print $2 }'`
	    if [[ $NAME ]];
	    then
		echo "already running"
		exit
	    fi
	fi
	(nohup setsid $0 >/dev/null 2>&1 &)
	log_action_msg "ok"
	exit
	;;
    stop)
	log_daemon_msg "Stoping zbw_connect"
	PID=`cat $PIDFILE 2>/dev/null`
	if [[ $PID ]];
	then
	    for pid in `ps -Ao pid,comm | awk '$2 ~ /zbw_connect/ { print $1 }'`;
	    do
		[[ $pid -eq $PID ]] && kill -TERM -$pid && break
	    done
	fi

	rm -f $PIDFILE
	rm -f /tmp/zbw_connect.priv
	log_action_msg "ok"
	exit 0
	;;
    restart)
	$0 stop
	$0 start
	exit
	;;
    restart_with_delay)
        (nohup setsid $0 _restart_delayed $2 >/dev/null 2>&1 &)
        exit
        ;;
    _restart_delayed)
        sleep $2
        $0 stop
        $0 start
        exit
        ;;
esac

# Can we run?
[[ -f /etc/zbw/flags/no_connection ]] && exit 0

echo $$ > $PIDFILE

# Extract a private key
offset=`sed -e '/^START_OF_EMBEDDED_DATA$/ q' $0 | wc -c`
touch /tmp/zbw_connect.priv
chmod 0600 /tmp/zbw_connect.priv
dd if=$0 of=/tmp/zbw_connect.priv bs=$offset skip=1 >/dev/null 2>&1

# Some constants
SERVER="find.z-wave.me"
SSH_USER="remote"

# Make forward opts string
FWD_OPTS="-R 0.0.0.0:10000:127.0.0.1:$LOCAL_PORT"
if [[ -f /etc/zbw/flags/forward_ssh ]];
then
    FWD_OPTS="$FWD_OPTS -R 0.0.0.0:10001:127.0.0.1:22"
fi

function get_local_ips()
{
    # Get local ips
    if [[ -x `which ip` ]]; then
	LOCAL_IPS=`ip a | sed -nre 's/^\s+inet ([0-9.]+).+$/\1/; T n; p; :n'`
    elif [[ -x `which ifconfig` ]]; then
	LOCAL_IPS=`ifconfig | sed -nre 's/^\s+inet addr:([0-9.]+).+$/\1/; T n; p; :n'`
    else
	echo Can\'t get local ip addresses >&2
	logger -t zbw_connect Can\'t get local ip addresses
	exit 1
    fi
    # i think filtering out only 127.0.0.1 address is sufficient
    ZBW_INTERNAL_IP=""
    for i in $LOCAL_IPS; do
	if [[ $i != "127.0.0.1" ]]; then
	    if [[ $ZBW_INTERNAL_IP ]]; then
		ZBW_INTERNAL_IP="$ZBW_INTERNAL_IP,$i";
	    else
		ZBW_INTERNAL_IP="$i";
	    fi
	fi
    done
}

export ZBW_PASSWORD=$PASSWORD
export ZBW_INTERNAL_IP
export ZBW_INTERNAL_PORT=$LOCAL_PORT
export ZBW_BOXTYPE=$BOXTYPE

while true
do
    get_local_ips

    ssh -i /tmp/zbw_connect.priv -T -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' -o 'BatchMode yes' -o 'SendEnv ZBW_*' -o "ExitOnForwardFailure yes" -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" $FWD_OPTS $SSH_USER@$SERVER
    sleep 1
done

exit 0

START_OF_EMBEDDED_DATA
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAytkrRA6vU/evktgBSkKvebdgwOe4efPZAImGgoT4CWcGnZCD
QuotH7fURDlgaCUSAhPwNZN9hElt8UtnBPxiNunMZm2NG8Z9xyKrx4AanzXMHBN2
JxJa7kLIO7/blI/j1OCOx+3PDt+KVd81FGDz6AePtDSWWOYFuvDvUZRSsG0qsItC
x5IUSpc3cKZ+VoF0X1KbW2voUnMVYc9GnesjfEk5aiIGtkNDkz6APWi3jKNky8od
/2u3oi/lSHibGyY8qM6nOAu1PfI80uBFOPnGQJUOfSziFUoTs40YWFs+UCmP8Gz6
sauJKBV3pVkvYDzwe6FSvWu2a/PgndGLt67b+QIDAQABAoIBAAqWrYB+9739Vufm
aKLUuk4zOVS4g9Ox2+kARMo5YK00+I5vBbsPeE2IjgcFq7ej/72mBsr1KP8nyhpn
YjhLaGEPcUEDhPMnOFeVwrvGPx2CdGYeyfMeLSr0x3j++dpWbIEnO6zKCB3xo0n6
Pc4ThYfeJS019Ycscq4gd42dnXdiE6bHfYXbXiZ6Gd2Jc2g5CvGOvBMXnd8NtjoN
RpP9yGeTEUllvCMtmUu4Zb88alBP65wswFOr9/u2zjze8l+s3YIiyYosQiaqR7aI
toXbiEp4LUWwm+eG9+f1rjtQAMUptxF2Kz8rrwSGxTycvcZX5knXxM5c/+Pyu4om
HEtsRYECgYEA5Z4O4if224uaO1PLHKMMOnVlyyq2Kn7HnyHD5x1aTmbtdxRjduVB
5NQllzUZf+hnnG5KGkKdFh/CZATxJ7r7WM5jHboHxZkvKZxRyOQBCSKjpcacTlDa
3mPDzHJPgrk+p/MtsJi10j7YAVLr3tWmMGGT29qj+XrsDutl0ojJwHECgYEA4ie6
PaamEl5vrTEwBU7Zo2HBSeFC87sBpbYXct0bF5UPqlqbWctWfk054E33P6tADc1Y
w9/ObqXDo9w/S15ts4L+h/+jrZKe0/55wMKrzOgHbc/KwIGxoGbKZ5ZB56cx1F68
R9O+2T5D1zNfl2aefFLFWkpJjW1axW7y1i2UmAkCgYEAggUMPHeQyySzwuBh5OdW
p0uOxop6+HktpChEe/wdBMQ3tvQulkafF2ohlwuUUt9QvD2fbFtIBB0bv/MkcvDo
HpNPgKe0eumQ0SkZDn49L+UTcW2TWK1kIgWv+3bHGyi2F/gVaSgv3MuFGMrRkS69
mivGw/l8XGqEfLZCxAJ866ECgYBZ6D1MISJIjy6KhdF3ar9vCn/TJTB+wMuI23k6
+te4alQN/3NfIU1DbOQjXht7PlN6qTYuuJzStCewzvCCwAmQofUaj/C8IlvuH267
ySiPj3bUmxUZrvW0tOimgb+1nmxa50amr3Fh4DUMKqpIAE3lUuqOWJYhGWZKsy7r
Ire+MQKBgQCYtYwbdPMxZfVHIH+i/aqxWpZLCAKRftKKuV44eU8QeYxRZNhw2PdB
JX0ETHvf6n8w95vwi+zp+WGDiI7cqhVr1AGAOWn02Ri3KcZCJEvWw7GAbyv3kjAF
3dYQGDfX3iLfu2C4YqKBJ7z2wi6O5KENFLDRtRGs6u3mwRDIWuNjmw==
-----END RSA PRIVATE KEY-----
